/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

dependencies {
    api(rootProject.libs.xerces.xercesimpl)
    api(rootProject.libs.org.apache.ant.ant)
    testImplementation(rootProject.libs.junit.junit)
}


java {
    withSourcesJar()
    withJavadocJar()
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    enabled = false
}
