/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "pentaho-mondrian-parent-pom"
include(":eigenbase-xom")
include(":eigenbase-properties")
include(":eigenbase-resgen")
include(":mondrian")

