/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "pentaho-mondrian-parent-pom"
include(":mondrian")
include(":pentaho-mondrian-assemblies")
include(":workbench")
include(":psw-ce")
project(":pentaho-mondrian-assemblies").projectDir = file("assemblies")
project(":psw-ce").projectDir = file("assemblies/psw-ce")
