/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("pentaho.java-conventions")
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion = "7.2"
}
tasks.register("prepareKotlinBuildScriptModel"){}

dependencies {
    api(libs.xml.apis.xml.apis)
    api(libs.commons.collections.commons.collections)
    api(libs.commons.dbcp.commons.dbcp)
    api(libs.commons.lang.commons.lang)
    api(libs.commons.io.commons.io)
    api(libs.commons.logging.commons.logging)
    api(libs.com.google.guava.guava)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.commons.math.commons.math)
    api(libs.commons.pool.commons.pool)
    api(libs.org.apache.commons.commons.vfs2)
    api(libs.org.dom4j.dom4j)
    api(libs.javax.validation.validation.api)
    api(libs.eigenbase.eigenbase.xom)
    api(libs.eigenbase.eigenbase.properties)
    api(libs.eigenbase.eigenbase.resgen)
    api(libs.org.olap4j.olap4j)
    api(libs.org.olap4j.olap4j.xmla)
    api(libs.xerces.xercesimpl)
    api(libs.javax.servlet.servlet.api)
    api(libs.javax.servlet.jsp.api)
    api(libs.javacup.javacup)
    api(libs.net.java.dev.javacc.javacc)
    testImplementation(libs.org.olap4j.olap4j.tck)
    testImplementation(libs.xmlunit.xmlunit)
    testImplementation(libs.org.mockito.mockito.all)
    testImplementation(libs.mysql.mysql.connector.java)
}

description = "Pentaho Community Edition Project: mondrian"
