/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

tasks {
    register("generateTestResources") {
        group = "build"
        doLast {
            ant.withGroovyBuilder {
                "taskdef"("name" to "resgen",
                        "classname" to "org.eigenbase.resgen.ResourceGenTask",
                        "classpath" to configurations.getByName("compileClasspath").asPath + ";" + sourceSets["main"].output.asPath)
                "resgen"("srcdir" to "src/test/java",
                        "resdir" to "src/test/resources",
                        "commentstyle" to "normal",
                        "locales" to "en_US,fr_FR") {
                    "include"("name" to "happy/BirthdayResource.xml")
                    "include"("name" to "happy/BirthdayResource_fr_FR.properties")
                }
            }
        }
    }

    register<Jar>("testJar") {
        from("build/classes")
        dependsOn(getByName("testClasses"))
    }
}

dependencies {
    api(project(":eigenbase-xom"))
    compileOnly(rootProject.libs.org.apache.ant.ant)
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    enabled = false
}

tasks.withType<Test>() {
    dependsOn(tasks.getByName("generateTestResources"))
    dependsOn(tasks.getByName("testJar"))
}
